######################################################################
# Automatically generated by qmake (2.01a) Tue Jan 22 00:28:38 2013
######################################################################

TEMPLATE = app
TARGET = kzoom
QT += dbus
DEPENDPATH += .
INCLUDEPATH += . ../common

# Input
HEADERS += ../common/ZoomWidget.h
FORMS += ../common/ZoomWidget.ui
SOURCES += main.cpp ../common/ZoomWidget.cpp
